// Generated by gencpp from file ouster_ros/OS1ConfigSrvRequest.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_OS1CONFIGSRVREQUEST_H
#define OUSTER_ROS_MESSAGE_OS1CONFIGSRVREQUEST_H


#include <string>
#include <vector>
#include <map>

#include <ros/types.h>
#include <ros/serialization.h>
#include <ros/builtin_message_traits.h>
#include <ros/message_operations.h>


namespace ouster_ros
{
template <class ContainerAllocator>
struct OS1ConfigSrvRequest_
{
  typedef OS1ConfigSrvRequest_<ContainerAllocator> Type;

  OS1ConfigSrvRequest_()
    {
    }
  OS1ConfigSrvRequest_(const ContainerAllocator& _alloc)
    {
  (void)_alloc;
    }







  typedef boost::shared_ptr< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> > Ptr;
  typedef boost::shared_ptr< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> const> ConstPtr;

}; // struct OS1ConfigSrvRequest_

typedef ::ouster_ros::OS1ConfigSrvRequest_<std::allocator<void> > OS1ConfigSrvRequest;

typedef boost::shared_ptr< ::ouster_ros::OS1ConfigSrvRequest > OS1ConfigSrvRequestPtr;
typedef boost::shared_ptr< ::ouster_ros::OS1ConfigSrvRequest const> OS1ConfigSrvRequestConstPtr;

// constants requiring out of line definition



template<typename ContainerAllocator>
std::ostream& operator<<(std::ostream& s, const ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> & v)
{
ros::message_operations::Printer< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >::stream(s, "", v);
return s;
}

} // namespace ouster_ros

namespace ros
{
namespace message_traits
{



// BOOLTRAITS {'IsFixedSize': True, 'IsMessage': True, 'HasHeader': False}
// {'sensor_msgs': ['/opt/ros/melodic/share/sensor_msgs/cmake/../msg'], 'ouster_ros': ['/home/lucerna/MEGAsync/project/AVP/avp_ws/src/ouster_ros/msg'], 'std_msgs': ['/opt/ros/melodic/share/std_msgs/cmake/../msg'], 'geometry_msgs': ['/opt/ros/melodic/share/geometry_msgs/cmake/../msg']}

// !!!!!!!!!!! ['__class__', '__delattr__', '__dict__', '__doc__', '__eq__', '__format__', '__getattribute__', '__hash__', '__init__', '__module__', '__ne__', '__new__', '__reduce__', '__reduce_ex__', '__repr__', '__setattr__', '__sizeof__', '__str__', '__subclasshook__', '__weakref__', '_parsed_fields', 'constants', 'fields', 'full_name', 'has_header', 'header_present', 'names', 'package', 'parsed_fields', 'short_name', 'text', 'types']




template <class ContainerAllocator>
struct IsFixedSize< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsFixedSize< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
  : TrueType
  { };

template <class ContainerAllocator>
struct IsMessage< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> const>
  : TrueType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
  : FalseType
  { };

template <class ContainerAllocator>
struct HasHeader< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> const>
  : FalseType
  { };


template<class ContainerAllocator>
struct MD5Sum< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "d41d8cd98f00b204e9800998ecf8427e";
  }

  static const char* value(const ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator>&) { return value(); }
  static const uint64_t static_value1 = 0xd41d8cd98f00b204ULL;
  static const uint64_t static_value2 = 0xe9800998ecf8427eULL;
};

template<class ContainerAllocator>
struct DataType< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "ouster_ros/OS1ConfigSrvRequest";
  }

  static const char* value(const ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator>&) { return value(); }
};

template<class ContainerAllocator>
struct Definition< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
{
  static const char* value()
  {
    return "\n"
;
  }

  static const char* value(const ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator>&) { return value(); }
};

} // namespace message_traits
} // namespace ros

namespace ros
{
namespace serialization
{

  template<class ContainerAllocator> struct Serializer< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
  {
    template<typename Stream, typename T> inline static void allInOne(Stream&, T)
    {}

    ROS_DECLARE_ALLINONE_SERIALIZER
  }; // struct OS1ConfigSrvRequest_

} // namespace serialization
} // namespace ros

namespace ros
{
namespace message_operations
{

template<class ContainerAllocator>
struct Printer< ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator> >
{
  template<typename Stream> static void stream(Stream&, const std::string&, const ::ouster_ros::OS1ConfigSrvRequest_<ContainerAllocator>&)
  {}
};

} // namespace message_operations
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_OS1CONFIGSRVREQUEST_H
