// Generated by gencpp from file ouster_ros/OS1ConfigSrv.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_OS1CONFIGSRV_H
#define OUSTER_ROS_MESSAGE_OS1CONFIGSRV_H

#include <ros/service_traits.h>


#include <ouster_ros/OS1ConfigSrvRequest.h>
#include <ouster_ros/OS1ConfigSrvResponse.h>


namespace ouster_ros
{

struct OS1ConfigSrv
{

typedef OS1ConfigSrvRequest Request;
typedef OS1ConfigSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OS1ConfigSrv
} // namespace ouster_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ouster_ros::OS1ConfigSrv > {
  static const char* value()
  {
    return "bb865a85fb3f39f43bf99730f10225b5";
  }

  static const char* value(const ::ouster_ros::OS1ConfigSrv&) { return value(); }
};

template<>
struct DataType< ::ouster_ros::OS1ConfigSrv > {
  static const char* value()
  {
    return "ouster_ros/OS1ConfigSrv";
  }

  static const char* value(const ::ouster_ros::OS1ConfigSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ouster_ros::OS1ConfigSrvRequest> should match 
// service_traits::MD5Sum< ::ouster_ros::OS1ConfigSrv > 
template<>
struct MD5Sum< ::ouster_ros::OS1ConfigSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::OS1ConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OS1ConfigSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::OS1ConfigSrvRequest> should match 
// service_traits::DataType< ::ouster_ros::OS1ConfigSrv > 
template<>
struct DataType< ::ouster_ros::OS1ConfigSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::OS1ConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OS1ConfigSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ouster_ros::OS1ConfigSrvResponse> should match 
// service_traits::MD5Sum< ::ouster_ros::OS1ConfigSrv > 
template<>
struct MD5Sum< ::ouster_ros::OS1ConfigSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::OS1ConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OS1ConfigSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::OS1ConfigSrvResponse> should match 
// service_traits::DataType< ::ouster_ros::OS1ConfigSrv > 
template<>
struct DataType< ::ouster_ros::OS1ConfigSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::OS1ConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OS1ConfigSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_OS1CONFIGSRV_H
