// Generated by gencpp from file ouster_ros/OSConfigSrv.msg
// DO NOT EDIT!


#ifndef OUSTER_ROS_MESSAGE_OSCONFIGSRV_H
#define OUSTER_ROS_MESSAGE_OSCONFIGSRV_H

#include <ros/service_traits.h>


#include <ouster_ros/OSConfigSrvRequest.h>
#include <ouster_ros/OSConfigSrvResponse.h>


namespace ouster_ros
{

struct OSConfigSrv
{

typedef OSConfigSrvRequest Request;
typedef OSConfigSrvResponse Response;
Request request;
Response response;

typedef Request RequestType;
typedef Response ResponseType;

}; // struct OSConfigSrv
} // namespace ouster_ros


namespace ros
{
namespace service_traits
{


template<>
struct MD5Sum< ::ouster_ros::OSConfigSrv > {
  static const char* value()
  {
    return "d37888e5a47bef783c189dec5351027e";
  }

  static const char* value(const ::ouster_ros::OSConfigSrv&) { return value(); }
};

template<>
struct DataType< ::ouster_ros::OSConfigSrv > {
  static const char* value()
  {
    return "ouster_ros/OSConfigSrv";
  }

  static const char* value(const ::ouster_ros::OSConfigSrv&) { return value(); }
};


// service_traits::MD5Sum< ::ouster_ros::OSConfigSrvRequest> should match
// service_traits::MD5Sum< ::ouster_ros::OSConfigSrv >
template<>
struct MD5Sum< ::ouster_ros::OSConfigSrvRequest>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::OSConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvRequest&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::OSConfigSrvRequest> should match
// service_traits::DataType< ::ouster_ros::OSConfigSrv >
template<>
struct DataType< ::ouster_ros::OSConfigSrvRequest>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::OSConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvRequest&)
  {
    return value();
  }
};

// service_traits::MD5Sum< ::ouster_ros::OSConfigSrvResponse> should match
// service_traits::MD5Sum< ::ouster_ros::OSConfigSrv >
template<>
struct MD5Sum< ::ouster_ros::OSConfigSrvResponse>
{
  static const char* value()
  {
    return MD5Sum< ::ouster_ros::OSConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvResponse&)
  {
    return value();
  }
};

// service_traits::DataType< ::ouster_ros::OSConfigSrvResponse> should match
// service_traits::DataType< ::ouster_ros::OSConfigSrv >
template<>
struct DataType< ::ouster_ros::OSConfigSrvResponse>
{
  static const char* value()
  {
    return DataType< ::ouster_ros::OSConfigSrv >::value();
  }
  static const char* value(const ::ouster_ros::OSConfigSrvResponse&)
  {
    return value();
  }
};

} // namespace service_traits
} // namespace ros

#endif // OUSTER_ROS_MESSAGE_OSCONFIGSRV_H
