(cl:in-package ouster_ros-srv)
(cl:export '(HOSTNAME-VAL
          HOSTNAME
          LIDAR_MODE-VAL
          LIDAR_MODE
          BEAM_AZIMUTH_ANGLES-VAL
          BEAM_AZIMUTH_ANGLES
          BEAM_ALTITUDE_ANGLES-VAL
          BEAM_ALTITUDE_ANGLES
          IMU_TO_SENSOR_TRANSFORM-VAL
          IMU_TO_SENSOR_TRANSFORM
          LIDAR_TO_SENSOR_TRANSFORM-VAL
          LIDAR_TO_SENSOR_TRANSFORM
))