; Auto-generated. Do not edit!


(cl:in-package ouster_ros-srv)


;//! \htmlinclude OS1ConfigSrv-request.msg.html

(cl:defclass <OS1ConfigSrv-request> (roslisp-msg-protocol:ros-message)
  ()
)

(cl:defclass OS1ConfigSrv-request (<OS1ConfigSrv-request>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OS1ConfigSrv-request>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OS1ConfigSrv-request)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ouster_ros-srv:<OS1ConfigSrv-request> is deprecated: use ouster_ros-srv:OS1ConfigSrv-request instead.")))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OS1ConfigSrv-request>) ostream)
  "Serializes a message object of type '<OS1ConfigSrv-request>"
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OS1ConfigSrv-request>) istream)
  "Deserializes a message object of type '<OS1ConfigSrv-request>"
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OS1ConfigSrv-request>)))
  "Returns string type for a service object of type '<OS1ConfigSrv-request>"
  "ouster_ros/OS1ConfigSrvRequest")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OS1ConfigSrv-request)))
  "Returns string type for a service object of type 'OS1ConfigSrv-request"
  "ouster_ros/OS1ConfigSrvRequest")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OS1ConfigSrv-request>)))
  "Returns md5sum for a message object of type '<OS1ConfigSrv-request>"
  "bb865a85fb3f39f43bf99730f10225b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OS1ConfigSrv-request)))
  "Returns md5sum for a message object of type 'OS1ConfigSrv-request"
  "bb865a85fb3f39f43bf99730f10225b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OS1ConfigSrv-request>)))
  "Returns full string definition for message of type '<OS1ConfigSrv-request>"
  (cl:format cl:nil "~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OS1ConfigSrv-request)))
  "Returns full string definition for message of type 'OS1ConfigSrv-request"
  (cl:format cl:nil "~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OS1ConfigSrv-request>))
  (cl:+ 0
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OS1ConfigSrv-request>))
  "Converts a ROS message object to a list"
  (cl:list 'OS1ConfigSrv-request
))
;//! \htmlinclude OS1ConfigSrv-response.msg.html

(cl:defclass <OS1ConfigSrv-response> (roslisp-msg-protocol:ros-message)
  ((hostname
    :reader hostname
    :initarg :hostname
    :type cl:string
    :initform "")
   (lidar_mode
    :reader lidar_mode
    :initarg :lidar_mode
    :type cl:string
    :initform "")
   (beam_azimuth_angles
    :reader beam_azimuth_angles
    :initarg :beam_azimuth_angles
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (beam_altitude_angles
    :reader beam_altitude_angles
    :initarg :beam_altitude_angles
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (imu_to_sensor_transform
    :reader imu_to_sensor_transform
    :initarg :imu_to_sensor_transform
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0))
   (lidar_to_sensor_transform
    :reader lidar_to_sensor_transform
    :initarg :lidar_to_sensor_transform
    :type (cl:vector cl:float)
   :initform (cl:make-array 0 :element-type 'cl:float :initial-element 0.0)))
)

(cl:defclass OS1ConfigSrv-response (<OS1ConfigSrv-response>)
  ())

(cl:defmethod cl:initialize-instance :after ((m <OS1ConfigSrv-response>) cl:&rest args)
  (cl:declare (cl:ignorable args))
  (cl:unless (cl:typep m 'OS1ConfigSrv-response)
    (roslisp-msg-protocol:msg-deprecation-warning "using old message class name ouster_ros-srv:<OS1ConfigSrv-response> is deprecated: use ouster_ros-srv:OS1ConfigSrv-response instead.")))

(cl:ensure-generic-function 'hostname-val :lambda-list '(m))
(cl:defmethod hostname-val ((m <OS1ConfigSrv-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ouster_ros-srv:hostname-val is deprecated.  Use ouster_ros-srv:hostname instead.")
  (hostname m))

(cl:ensure-generic-function 'lidar_mode-val :lambda-list '(m))
(cl:defmethod lidar_mode-val ((m <OS1ConfigSrv-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ouster_ros-srv:lidar_mode-val is deprecated.  Use ouster_ros-srv:lidar_mode instead.")
  (lidar_mode m))

(cl:ensure-generic-function 'beam_azimuth_angles-val :lambda-list '(m))
(cl:defmethod beam_azimuth_angles-val ((m <OS1ConfigSrv-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ouster_ros-srv:beam_azimuth_angles-val is deprecated.  Use ouster_ros-srv:beam_azimuth_angles instead.")
  (beam_azimuth_angles m))

(cl:ensure-generic-function 'beam_altitude_angles-val :lambda-list '(m))
(cl:defmethod beam_altitude_angles-val ((m <OS1ConfigSrv-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ouster_ros-srv:beam_altitude_angles-val is deprecated.  Use ouster_ros-srv:beam_altitude_angles instead.")
  (beam_altitude_angles m))

(cl:ensure-generic-function 'imu_to_sensor_transform-val :lambda-list '(m))
(cl:defmethod imu_to_sensor_transform-val ((m <OS1ConfigSrv-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ouster_ros-srv:imu_to_sensor_transform-val is deprecated.  Use ouster_ros-srv:imu_to_sensor_transform instead.")
  (imu_to_sensor_transform m))

(cl:ensure-generic-function 'lidar_to_sensor_transform-val :lambda-list '(m))
(cl:defmethod lidar_to_sensor_transform-val ((m <OS1ConfigSrv-response>))
  (roslisp-msg-protocol:msg-deprecation-warning "Using old-style slot reader ouster_ros-srv:lidar_to_sensor_transform-val is deprecated.  Use ouster_ros-srv:lidar_to_sensor_transform instead.")
  (lidar_to_sensor_transform m))
(cl:defmethod roslisp-msg-protocol:serialize ((msg <OS1ConfigSrv-response>) ostream)
  "Serializes a message object of type '<OS1ConfigSrv-response>"
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'hostname))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'hostname))
  (cl:let ((__ros_str_len (cl:length (cl:slot-value msg 'lidar_mode))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_str_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_str_len) ostream))
  (cl:map cl:nil #'(cl:lambda (c) (cl:write-byte (cl:char-code c) ostream)) (cl:slot-value msg 'lidar_mode))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'beam_azimuth_angles))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'beam_azimuth_angles))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'beam_altitude_angles))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'beam_altitude_angles))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'imu_to_sensor_transform))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'imu_to_sensor_transform))
  (cl:let ((__ros_arr_len (cl:length (cl:slot-value msg 'lidar_to_sensor_transform))))
    (cl:write-byte (cl:ldb (cl:byte 8 0) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) __ros_arr_len) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) __ros_arr_len) ostream))
  (cl:map cl:nil #'(cl:lambda (ele) (cl:let ((bits (roslisp-utils:encode-double-float-bits ele)))
    (cl:write-byte (cl:ldb (cl:byte 8 0) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 8) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 16) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 24) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 32) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 40) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 48) bits) ostream)
    (cl:write-byte (cl:ldb (cl:byte 8 56) bits) ostream)))
   (cl:slot-value msg 'lidar_to_sensor_transform))
)
(cl:defmethod roslisp-msg-protocol:deserialize ((msg <OS1ConfigSrv-response>) istream)
  "Deserializes a message object of type '<OS1ConfigSrv-response>"
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'hostname) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'hostname) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
    (cl:let ((__ros_str_len 0))
      (cl:setf (cl:ldb (cl:byte 8 0) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) __ros_str_len) (cl:read-byte istream))
      (cl:setf (cl:slot-value msg 'lidar_mode) (cl:make-string __ros_str_len))
      (cl:dotimes (__ros_str_idx __ros_str_len msg)
        (cl:setf (cl:char (cl:slot-value msg 'lidar_mode) __ros_str_idx) (cl:code-char (cl:read-byte istream)))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'beam_azimuth_angles) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'beam_azimuth_angles)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'beam_altitude_angles) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'beam_altitude_angles)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'imu_to_sensor_transform) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'imu_to_sensor_transform)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  (cl:let ((__ros_arr_len 0))
    (cl:setf (cl:ldb (cl:byte 8 0) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 8) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 16) __ros_arr_len) (cl:read-byte istream))
    (cl:setf (cl:ldb (cl:byte 8 24) __ros_arr_len) (cl:read-byte istream))
  (cl:setf (cl:slot-value msg 'lidar_to_sensor_transform) (cl:make-array __ros_arr_len))
  (cl:let ((vals (cl:slot-value msg 'lidar_to_sensor_transform)))
    (cl:dotimes (i __ros_arr_len)
    (cl:let ((bits 0))
      (cl:setf (cl:ldb (cl:byte 8 0) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 8) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 16) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 24) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 32) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 40) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 48) bits) (cl:read-byte istream))
      (cl:setf (cl:ldb (cl:byte 8 56) bits) (cl:read-byte istream))
    (cl:setf (cl:aref vals i) (roslisp-utils:decode-double-float-bits bits))))))
  msg
)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql '<OS1ConfigSrv-response>)))
  "Returns string type for a service object of type '<OS1ConfigSrv-response>"
  "ouster_ros/OS1ConfigSrvResponse")
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OS1ConfigSrv-response)))
  "Returns string type for a service object of type 'OS1ConfigSrv-response"
  "ouster_ros/OS1ConfigSrvResponse")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql '<OS1ConfigSrv-response>)))
  "Returns md5sum for a message object of type '<OS1ConfigSrv-response>"
  "bb865a85fb3f39f43bf99730f10225b5")
(cl:defmethod roslisp-msg-protocol:md5sum ((type (cl:eql 'OS1ConfigSrv-response)))
  "Returns md5sum for a message object of type 'OS1ConfigSrv-response"
  "bb865a85fb3f39f43bf99730f10225b5")
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql '<OS1ConfigSrv-response>)))
  "Returns full string definition for message of type '<OS1ConfigSrv-response>"
  (cl:format cl:nil "string hostname~%string lidar_mode~%float64[] beam_azimuth_angles~%float64[] beam_altitude_angles~%float64[] imu_to_sensor_transform~%float64[] lidar_to_sensor_transform~%~%~%"))
(cl:defmethod roslisp-msg-protocol:message-definition ((type (cl:eql 'OS1ConfigSrv-response)))
  "Returns full string definition for message of type 'OS1ConfigSrv-response"
  (cl:format cl:nil "string hostname~%string lidar_mode~%float64[] beam_azimuth_angles~%float64[] beam_altitude_angles~%float64[] imu_to_sensor_transform~%float64[] lidar_to_sensor_transform~%~%~%"))
(cl:defmethod roslisp-msg-protocol:serialization-length ((msg <OS1ConfigSrv-response>))
  (cl:+ 0
     4 (cl:length (cl:slot-value msg 'hostname))
     4 (cl:length (cl:slot-value msg 'lidar_mode))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'beam_azimuth_angles) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'beam_altitude_angles) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'imu_to_sensor_transform) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
     4 (cl:reduce #'cl:+ (cl:slot-value msg 'lidar_to_sensor_transform) :key #'(cl:lambda (ele) (cl:declare (cl:ignorable ele)) (cl:+ 8)))
))
(cl:defmethod roslisp-msg-protocol:ros-message-to-list ((msg <OS1ConfigSrv-response>))
  "Converts a ROS message object to a list"
  (cl:list 'OS1ConfigSrv-response
    (cl:cons ':hostname (hostname msg))
    (cl:cons ':lidar_mode (lidar_mode msg))
    (cl:cons ':beam_azimuth_angles (beam_azimuth_angles msg))
    (cl:cons ':beam_altitude_angles (beam_altitude_angles msg))
    (cl:cons ':imu_to_sensor_transform (imu_to_sensor_transform msg))
    (cl:cons ':lidar_to_sensor_transform (lidar_to_sensor_transform msg))
))
(cl:defmethod roslisp-msg-protocol:service-request-type ((msg (cl:eql 'OS1ConfigSrv)))
  'OS1ConfigSrv-request)
(cl:defmethod roslisp-msg-protocol:service-response-type ((msg (cl:eql 'OS1ConfigSrv)))
  'OS1ConfigSrv-response)
(cl:defmethod roslisp-msg-protocol:ros-datatype ((msg (cl:eql 'OS1ConfigSrv)))
  "Returns string type for a service object of type '<OS1ConfigSrv>"
  "ouster_ros/OS1ConfigSrv")